services:
  mysql:
    image: mysql:9
    container_name: iron_dome_mysql
    restart: always

    env_file:
      - db.env

    ports:
      - "3306:3306"

    volumes:
      - ironDomeMysql:/var/lib/mysql

  app:
    build: ./
    container_name: iron_dome_server
    working_dir: /app
    depends_on:
      - mysql
    restart: always

    env_file:
      - .env

    ports:
      - "3000:3000"

    volumes:
      - ./:/app

volumes:
  ironDomeMysql:
    


  

  