services:
  mysql:
    image: mysql:9
    container_name: iron_dome_mysql
    restart: always
    env_file:
      - db.env
    ports:
      - "3306:3306"

    volumes:
      - iromDomeMysql:/var/lib/mysql

  app:
    build: ./
    container_name: iron_dome_server
    depends_on:
      - mysql
    working_dir: /app
    volumes:
      - "./:/app"
    ports:
     - "3000:3000"
    env_file:
      - .env




volumes:
  iromDomeMysql:


